use_frameworks!
platform :ios, '9.0'

target 'Salsa20Cipher_Example' do
  pod 'Salsa20Cipher', :path => '../'
  pod 'SwiftLint'
end

target 'Salsa20Cipher_Tests' do
  inherit! :search_paths
  pod 'Salsa20Cipher', :path => '../'
  #  pod 'CleanTests', :git => 'https://github.com/igorkotkovets/pod.swift.clean-tests.git'
  pod 'CleanTests', :path => '../../../github/swift.pod.clean-tests'
end
